"use server"

import { revalidatePath } from 'next/cache'
import { getSupabaseAdmin } from '@/lib/supabase/admin'
import { createClient } from '@/lib/supabase/server'
import { logAudit } from './audit'

async function ensureSuperadmin() {
  const supabase = await createClient()
  const { data: { user }, error } = await supabase.auth.getUser()
  if (error || !user) throw new Error("Unauthorized")
  
  if (user.user_metadata?.role !== 'super_admin') {
    throw new Error("Forbidden: Superadmin access required")
  }

  const adminClient = getSupabaseAdmin()
  const { data: profile } = await adminClient
    .from('staff_profiles')
    .select('status')
    .eq('id', user.id)
    .single()

  if (profile?.status === 'suspended') {
    throw new Error("Forbidden: Your account is suspended")
  }

  return user.id
}

export async function checkEmailUniqueness(email: string) {
  await ensureSuperadmin()
  const adminClient = getSupabaseAdmin()
  
  // We check the staff_profiles table, since work_email is unique there
  const { count } = await adminClient
    .from('staff_profiles')
    .select('*', { count: 'exact', head: true })
    .eq('work_email', email)
    
  return count === 0
}

export async function createStaffUser(formData: FormData) {
  try {
    await ensureSuperadmin()
    
    const firstName = formData.get('first_name') as string
    const lastName = formData.get('last_name') as string
    const designation = formData.get('designation') as string
    const emailPrefix = formData.get('email_prefix') as string
    const temporaryPassword = formData.get('temporary_password') as string
    
    if (!firstName || !lastName || !designation || !emailPrefix || !temporaryPassword) {
      return { error: 'All fields are required' }
    }
    
    const workEmail = `${emailPrefix.toLowerCase().trim()}@lamweb.com`
    const isUnique = await checkEmailUniqueness(workEmail)
    
    if (!isUnique) {
      return { error: 'Generated email is already in use' }
    }
    
    const adminClient = getSupabaseAdmin()
    
    // 1. Create auth user using Service Role
    const { data: authData, error: authError } = await adminClient.auth.admin.createUser({
      email: workEmail,
      password: temporaryPassword,
      email_confirm: true,
      user_metadata: {
        role: 'staff'
      }
    })
    
    if (authError) {
      return { error: authError.message }
    }
    
    if (!authData.user) {
      return { error: 'Failed to create user account' }
    }
    
    // 2. Insert into staff_profiles (staff_id is generated by DB)
    const { error: profileError } = await adminClient
      .from('staff_profiles')
      .insert({
        id: authData.user.id,
        first_name: firstName,
        last_name: lastName,
        designation: designation,
        work_email: workEmail,
        status: 'active',
        requires_password_change: true
      })
      
    if (profileError) {
      await adminClient.auth.admin.deleteUser(authData.user.id)
      return { error: `Failed to create profile: ${profileError.message}` }
    }
    
    // 3. Insert permissions
    const permissionsStr = formData.get('permissions') as string
    const permissionsObj = permissionsStr ? JSON.parse(permissionsStr) : {}
    
    const { error: permError } = await adminClient
      .from('staff_permissions')
      .insert({
        user_id: authData.user.id,
        permissions: permissionsObj
      })
      
    if (permError) {
      console.error("Failed to insert permissions:", permError)
      // Non-fatal for creation, can be edited later
    }
    
    // 4. Insert default settings
    const { error: settingsError } = await adminClient
      .from('staff_settings')
      .insert({
        user_id: authData.user.id
      })
      
    if (settingsError) {
      console.error("Failed to insert default settings:", settingsError)
    }
    
    await logAudit('staff_profile', authData.user.id, 'create', {
      first_name: firstName,
      last_name: lastName,
      designation: designation,
      work_email: workEmail,
      permissions: permissionsObj
    })

    revalidatePath('/control-panel/users')
    return { success: true }
    
  } catch (err: unknown) {
    return { error: (err as Error).message || 'An unexpected error occurred' }
  }
}

export async function toggleUserStatus(userId: string, currentStatus: string) {
  try {
    const currentUserId = await ensureSuperadmin()
    
    if (userId === currentUserId) {
      return { error: 'You cannot suspend your own account.' }
    }

    const adminClient = getSupabaseAdmin()
    
    const newStatus = currentStatus === 'active' ? 'suspended' : 'active'
    
    const { error } = await adminClient
      .from('staff_profiles')
      .update({ status: newStatus })
      .eq('id', userId)
      
    if (error) {
      return { error: error.message }
    }
    
    await logAudit('staff_profile', userId, 'status_change', { new_status: newStatus })

    revalidatePath('/control-panel/users')
    return { success: true }
  } catch (err: unknown) {
    return { error: (err as Error).message || 'An unexpected error occurred' }
  }
}

export async function saveUserPermissions(targetUserId: string, newPermissions: Record<string, string[]>) {
  try {
    await ensureSuperadmin()
    const supabase = await createClient()
    const { data: { user: currentUser } } = await supabase.auth.getUser()
    const adminClient = getSupabaseAdmin()

    // Anti-lockout: if target is the current user, they cannot remove access_permissions or user_management
    if (targetUserId === currentUser?.id) {
      if (!newPermissions.access_permissions || !newPermissions.user_management) {
        return { error: 'You cannot remove your own Access & Permissions or User Management modules.' }
      }
    }

    // Anti-lockout: verify we aren't removing the last superadmin
    if (!newPermissions.access_permissions || !newPermissions.user_management) {
      // Check if this user currently has them
      const { data: oldPermData } = await adminClient
        .from('staff_permissions')
        .select('permissions')
        .eq('user_id', targetUserId)
        .single()
        
      const hadAdmin = oldPermData?.permissions?.access_permissions && oldPermData?.permissions?.user_management
      
      if (hadAdmin) {
        // Are there other admins?
        const { count } = await adminClient
          .from('staff_permissions')
          .select('*', { count: 'exact', head: true })
          .neq('user_id', targetUserId)
          .contains('permissions', { access_permissions: ['view'], user_management: ['view'] })
          
        if (count === 0) {
          return { error: 'Cannot remove admin permissions: This is the last active Administrator account.' }
        }
      }
    }

    // Get old permissions for audit log
    const { data: oldData } = await adminClient
      .from('staff_permissions')
      .select('permissions')
      .eq('user_id', targetUserId)
      .maybeSingle()

    // Upsert new permissions
    const { error: upsertError } = await adminClient
      .from('staff_permissions')
      .upsert({
        user_id: targetUserId,
        permissions: newPermissions,
        updated_by: currentUser?.id
      })

    if (upsertError) return { error: upsertError.message }

    // Log Audit
    await logAudit('staff_permissions', targetUserId, 'update', {
      old: oldData?.permissions || {},
      new: newPermissions
    })

    revalidatePath('/control-panel/users')
    revalidatePath('/control-panel/layout') // Force layout update for sidebar
    return { success: true }
  } catch (err: unknown) {
    return { error: (err as Error).message || 'An unexpected error occurred' }
  }
}
